#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)


if [ "$current_branch" = "$protected_branch" ]; then
    echo "\n\nDirect commits to the branch \"$protected_branch\" are not allowed\n\n"
    exit 1
else
  npm run fix-lint-staged
  npm test
fi

exit 0