#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if  [ "$current_branch" = "$protected_branch" ]; then
  echo "\n\nNever push code directly to the \"$protected_branch\" branch!\n\n"
  exit 1
fi