name: Code Sec scans

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
  njsscan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@v6
        with:
          args: "."
  npm-audit:
    strategy:
      matrix:
        node-version: ["16.13.2"]
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - uses: oke-py/npm-audit-action@v1.7.3
        with:
          production_flag: true
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: ioannis-karasavvaidis
          issue_labels: vulnerability
          dedupe_issues: true